### ISSUE TITLE
Installing browserless via npm throws an error

### ISSUE THREAD

**Issue by davidchai717** [microlinkhq/browserless#250]
### Prerequisites

- [ x] I'm using the last version.
- [ x] My node version is the same as declared as `package.json`.

### Subject of the issue

Installing browserless via npm would fail and throw an error:

```> top-user-agents@1.0.20 postinstall /Project/node_modules/top-user-agents
> node scripts/postinstall

/Project/node_modules/hooman/hooman.js:14
const instance = got.extend({
                     ^

TypeError: got.extend is not a function
    at Object.<anonymous> (/Project/node_modules/hooman/hooman.js:14:22)
    at Module._compile (internal/modules/cjs/loader.js:1133:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1153:10)
    at Module.load (internal/modules/cjs/loader.js:977:32)
    at Function.Module._load (internal/modules/cjs/loader.js:877:14)
    at Module.require (internal/modules/cjs/loader.js:1019:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (/Project/node_modules/top-user-agents/scripts/postinstall.js:5:13)
    at Module._compile (internal/modules/cjs/loader.js:1133:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1153:10)
```

### Steps to reproduce

> **Note**: You can reproduce the code using [interactive Node.js shell by Runkit](https://npm.runkit.com/metascraper).

```npm i -S browserless```

**Comment by Kikobeats** [comment]
I try to reproduce and I didn't find a problem.

Looks like the place where you are trying to install `browserless` is using an old npm version that is not installing `got` properly.

can you try to run and paste the output for:

- npm --version
- node --version
- npm ls
