### ISSUE TITLE
Using SocksProxyAgent fails

### ISSUE THREAD

**Issue by ppatrzyk** [microlinkhq/browserless#301]
### Prerequisites

- [x] I'm using the last version. (9.1.6)
- [x] My node version is the same as declared as `package.json`. (v14.17.5)

### Subject of the issue

Trying to use proxy as described in [documentation](https://browserless.js.org/#/?id=agent) results in error for me. Could you advise what is the proper way to define it? In past issues I only found some other way, not described in the docs ( https://github.com/microlinkhq/browserless/issues/259 ). Thanks

### Steps to reproduce

```
const browserless = require('browserless')
const { SocksProxyAgent } = require('socks-proxy-agent')

function testf(url) {
    (async () => {
        const browserless_factory = browserless()
        const browser = await browserless_factory.createContext({
            // agent: undefined
            agent: new SocksProxyAgent({
                host: 'localhost',
                port: 9050
            })
        })
        page_content = await browser.html(url)
        await browser.destroyContext();
        console.log(page_content)
    })()
}

testf('http://ip-api.com/json')
```

### Expected behaviour

Requests made through specified proxy.

### Actual behaviour

Running the script above results in the following error:

```
(node:29627) UnhandledPromiseRejectionWarning: Error: Request is already handled!
    at Object.assert (<MY_PATH>/node_modules/puppeteer/lib/cjs/puppeteer/common/assert.js:26:15)
    at HTTPRequest.continue (<MY_PATH>/node_modules/puppeteer/lib/cjs/puppeteer/common/HTTPRequest.js:283:21)
    at PuppeteerBlocker.onRequest (<MY_PATH>/node_modules/@cliqz/adblocker-puppeteer/dist/cjs/adblocker.js:225:33)
    at BlockingContext.onRequest (<MY_PATH>/node_modules/@cliqz/adblocker-puppeteer/dist/cjs/adblocker.js:65:47)
    at <MY_PATH>/node_modules/puppeteer/lib/cjs/puppeteer/common/Page.js:226:52
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async HTTPRequest.finalizeInterceptions (<MY_PATH>/node_modules/puppeteer/lib/cjs/puppeteer/common/HTTPRequest.js:132:9)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:29627) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:29627) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Note that everything works ok if I change `agent` to undefined.

**Comment by Kikobeats** [comment]
I'm getting that error too, but the proxy is doing the job.

So not sure if the error there is legit or no. Is your proxy doing the job?

Related: https://github.com/puppeteer/puppeteer/issues/5334

**Comment by ppatrzyk** [comment]
> Is your proxy doing the job?

Yes, it works as expected with e.g. `curl --socks5 localhost:9050 http://ip-api.com/json`

Here I'm only getting this error, followed by an empty response from the browser

**Comment by Kikobeats** [comment]
I mean if even the code is reporting that error message is the proxy passed thought browserless doing the job?
