### ISSUE TITLE
Sample from documentation site not working out of the box

### ISSUE THREAD

**Issue by nalmeida** [microlinkhq/browserless#311]
### Prerequisites

- [X] I'm using the last version.
- [X] My node version is the same as declared as `package.json`.

### Subject of the issue

My environment:
- nvm: `0.38.0`
- node: `v12.22.6`
- npm: `6.14.15`

Just want to test browserless following the starting guide from documentation but I am getting the error:

```bash
const browserless = await browserlessFactory.createContext()
                    ^^^^^

SyntaxError: await is only valid in async function
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
    at internal/main/run_main_module.js:17:47
```

#### Installing

```bash
mkdir test
cd test
nvm use v12.22.6
npm init -y
npm install browserless puppeteer --save
```

#### Sample project

```bash
touch index.js
```

##### `index.js` content

```javascript
const createBrowserless = require('browserless')
const termImg = require('term-img')

// First, create a browserless factory 
// that it will keep a singleton process running
const browserlessFactory = createBrowserless()

// After that, you can create as many browser context
// as you need. The browser contexts won't share cookies/cache 
// with other browser contexts.
const browserless = await browserlessFactory.createContext()

// Perform the action you want, e.g., getting the HTML markup
const buffer = await browserless.screenshot('https://basecamp.com', {
  device: 'iPhone 6'
})

console.log(termImg(buffer))

// After your task is done, destroy your browser context
await browserless.destroyContext()

// At the end, gracefully shutdown the browser process
await browserless.close()
```

##### Running

```bash
node index.js
```

Runningkit: https://runkit.com/embed/a7xjdfhnz7xi

**Comment by Kikobeats** [comment]
Node.js doesn't allow async at the top level.

You should call the async code inside a function

Related: https://github.com/robertklep/top-level-await
